# Keyword configuration for news filtering and ranking
# Keywords are used to determine event importance and relevance

high_priority_keywords:
  # Critical system issues requiring immediate attention
  - "outage"
  - "breach" 
  - "critical"
  - "ransomware"
  - "exploit"
  - "vulnerability"
  - "compromise"
  - "incident"
  - "failure"
  - "emergency"
  - "identity theft"
  - "hijacking"

medium_priority_keywords:
  # Important updates and security-related items
  - "patch"
  - "security"
  - "alert"
  - "maintenance"
  - "warning"
  - "issue"
  - "fix"
  - "downgrade"
  - "backup"
  - "firewall"
  - "authentication"
  - "virus"
  - "trojan"

low_priority_keywords:
  # General information and announcements
  - "info"
  - "announcement"
  - "release"
  - "notice"
  - "roadmap"
  - "upgrade"
  - "version"
