
- name: "Sysadmin"
  type: "reddit"
  subreddit_name: "sysadmin"
  limit: 2

- name: "Ars Technica"
  type: "rss"
  url: "https://feeds.arstechnica.com/arstechnica/index"
  limit: 2

- name: "Tom's Hardware"
  type: "rss"
  url: "https://www.tomshardware.com/feeds.xml"
  limit: 2


